Replace the first letter to a capital letter
js-tasks-ru/jsbasic-20210225_atlas2012 pull request #3
Opened 2021-03-03 21:12 UTC by Atlas2012

2021-03-03 21:12 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 1-module/3-task/task.test.js — добавлен
```

2021-03-03 21:19 UTC, Atlas2012 commented
мне тут ругается на изменения в test.js
видимо случайно что-то тыкнул, а где посмотреть оригинальный файл?

2021-03-04 20:17 UTC, SinimaWath requested changes

2021-03-04 20:17 UTC, SinimaWath commented on 1-module/3-task/index.js
> +alert(ucFirst('вася'));
Дебаг-информация, видимо забыл убрать :)

2021-03-04 20:17 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  return str.charAt(0).toUpperCase() + str.slice(1);
В JS принят такой стиль написания кода:
```
if (!str) {
  return str;
}

return ....
```

Лучше всегда явно указывать { }

2021-03-04 20:53 UTC, SinimaWath approved these changes

2021-03-04 20:53 UTC, merged